// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL4U3yrvmQrnSw3nz69Z3oGjUKuk7QR00',
    appId: '1:81092737274:web:6bf39102c95765eb00b143',
    messagingSenderId: '81092737274',
    projectId: 'currensee-app-70ce6',
    authDomain: 'currensee-app-70ce6.firebaseapp.com',
    storageBucket: 'currensee-app-70ce6.firebasestorage.app',
    measurementId: 'G-V16DN8N5PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatezqrirDZPql3OvDGPum_7Pkgqj38EM',
    appId: '1:81092737274:android:3ab272b7ef9044a300b143',
    messagingSenderId: '81092737274',
    projectId: 'currensee-app-70ce6',
    storageBucket: 'currensee-app-70ce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx2ElKc_Gg5Fshun5Z5appCNZgjbQqJaE',
    appId: '1:81092737274:ios:ad49b25caf3ca7a600b143',
    messagingSenderId: '81092737274',
    projectId: 'currensee-app-70ce6',
    storageBucket: 'currensee-app-70ce6.firebasestorage.app',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx2ElKc_Gg5Fshun5Z5appCNZgjbQqJaE',
    appId: '1:81092737274:ios:ad49b25caf3ca7a600b143',
    messagingSenderId: '81092737274',
    projectId: 'currensee-app-70ce6',
    storageBucket: 'currensee-app-70ce6.firebasestorage.app',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL4U3yrvmQrnSw3nz69Z3oGjUKuk7QR00',
    appId: '1:81092737274:web:537678c56b16acf800b143',
    messagingSenderId: '81092737274',
    projectId: 'currensee-app-70ce6',
    authDomain: 'currensee-app-70ce6.firebaseapp.com',
    storageBucket: 'currensee-app-70ce6.firebasestorage.app',
    measurementId: 'G-HQ8BX4QN7S',
  );

}